# Generated by Django 5.0.1 on 2024-03-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
